[platformio]
default_envs = stm32f107custom

[env:stm32f107custom]
platform = ststm32
board = genericSTM32F107VC
framework = stm32cube

build_type = debug
debug_tool = stlink
upload_protocol = stlink
debug_init_break = break loop

lib_deps =
  lvgl/lvgl@^8.3.11

build_unflags =
    -std=gnu++11

build_flags =
  -std=gnu++17
  -std=gnu11
  -fexceptions
  -Wall
  -Wextra
  -Wno-unused-parameter  
  -DDEBUG=1
  -DDEBUG_OUTPUT=DEBUG_OUTPUT_SWD
  ; -DDEBUG_OUTPUT=DEBUG_OUTPUT_NONE
  ; -DDEBUG_OUTPUT=DEBUG_OUTPUT_USB
  -DTFT_DRIVER=TFT_DRIVER_ST7789
  -DLV_CONF_INCLUDE_SIMPLE
  -I include
  -Og
  -g3
