[platformio]
default_envs = stm32f107custom
; default_envs = stm32f107custom_usb
; default_envs = stm32f107custom_swo

src_dir = .

[env:stm32f107custom_base]
platform = ststm32
board = genericSTM32F107VC
framework = stm32cube

build_type = debug
; build_type = release
debug_tool = stlink
upload_protocol = stlink
debug_init_break = break loop

lib_deps =
  lvgl/lvgl@^8.3.11

build_src_filter =
  +<src/>
  -<.git>
  -<.vscode>
  -<.pio>
  -<.pio_tmp>
  -<docs>
  -<scripts>
  -<test>
  -<examples>

build_unflags =
    -std=gnu++11

; === debug flags ===
; DEBUG=1 enable debugging
; DEBUG_OUTPUT=<DEBUG_OUTPUT_NONE/DEBUG_OUTPUT_SWO> select debug output. if DEBUG=0, this will be set to DEBUG_OUTPUT_NONE
; LV_MEM_DEBUG=1 enable memory debugging/monitoring
; LV_USE_LOG=1 enable LVGL logging

build_flags =
  -std=gnu++17
  -std=gnu11
  -fno-exceptions
  -Wall
  -Wextra
  -Wno-unused-parameter
  -D DEBUG=1
  -D TFT_DRIVER=TFT_DRIVER_ST7789
  -D LV_CONF_INCLUDE_SIMPLE
  -D HAVE_MOTOR_VIBES        ; +496 byte
  -D HAVE_IMPERIAL_MARCH     ; total +916 byte (+420 byte from HAVE_MOTOR_VIBES which is required)
  -I include
  -Og
  -g3

; -------------------------------------------------------------------------
; USB debugging and SWO tuning
; -------------------------------------------------------------------------
[env:stm32f107custom_usb]
extends = env:stm32f107custom_base

build_src_filter = ${env:stm32f107custom_base.build_src_filter}
  +<cubemx/USB_DEVICE/App/>
  +<cubemx/USB_DEVICE/Target/usbd_conf.c>
  +<cubemx/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c>
  +<cubemx/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c>
  +<cubemx/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c>
  +<cubemx/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c>

build_flags =
  ${env:stm32f107custom_base.build_flags}
  -D HAVE_USB_DEVICE=1                       ; +10096byte for the usb stack
  -D DEBUG_OUTPUT=DEBUG_OUTPUT_SWO
  -D HAVE_SWO_SCREENSHOTS
  -I cubemx/Core/Inc
  -I cubemx/USB_DEVICE/App
  -I cubemx/USB_DEVICE/Target
  -I cubemx/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  -I cubemx/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc

monitor_speed = 115200
monitor_port = COM10

; -------------------------------------------------------------------------
; SWO debugging/tuning and no USB support
; -------------------------------------------------------------------------
[env:stm32f107custom_swo]
extends = env:stm32f107custom_base

build_flags =
  ${env:stm32f107custom_base.build_flags}
  -D HAVE_USB_DEVICE=0
  -D DEBUG_OUTPUT=DEBUG_OUTPUT_SWO
  -D HAVE_SWO_SCREENSHOTS
  ; -D HAVE_DWT_TICK_PROFILER
  ; -D LV_USE_PERF_MONITOR
  ; -D LV_USE_MEM_MONITOR
  ; -D LV_USE_LOG
  ; -D LV_MEM_DEBUG

; -------------------------------------------------------------------------
; default... extends stm32f107custom_XXX to keep filenames the same
; -------------------------------------------------------------------------
[env:stm32f107custom]
extends = env:stm32f107custom_usb
