[platformio]
default_envs = stm32f107custom

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

upload_protocol = serial
upload_port = COM7
upload_speed = 115200
upload_flags =
  -b
  115200

monitor_speed = 115200

lib_deps =
  lvgl/lvgl@^8.3.11

build_flags =
  -DTFT_DRIVER_ST7735=1
  -DLV_CONF_INCLUDE_SIMPLE
  -I include

[env:stm32f107custom]
platform = ststm32
board = genericSTM32F107VC
framework = arduino
build_type = debug
debug_tool = stlink
upload_protocol = stlink
debug_init_break = break loop

lib_deps =
  lvgl/lvgl@^8.3.11

build_flags =
  -DDEBUG_OUTPUT=DEBUG_OUTPUT_SWD
  -DTFT_DRIVER=TFT_DRIVER_ST7789
  -DLV_CONF_INCLUDE_SIMPLE
  -I include
  -Wl,-u,_printf_float
